class RuleEngine:
    def __init__(self):
        self.rules = []

    def add_rule(self, condition, response):
        self.rules.append({"condition": condition, "response": response})

    def apply_rules(self, text):
        for rule in self.rules:
            if rule["condition"] in text.lower():
                return f"Bot: {rule['response']}"
        return "Bot: I don't understand."

# Example usage
rule_engine = RuleEngine()

# Add rules
rule_engine.add_rule("suggest a movie", "How about watching Inception?")
rule_engine.add_rule("recommend a movie", "You might enjoy The Shawshank Redemption.")
rule_engine.add_rule("what movie should I watch", "Try watching Interstellar.")
rule_engine.add_rule("movie recommendation", "The Godfather is a classic choice.")
rule_engine.add_rule("I want to watch something funny", "Superbad is a great comedy!")
rule_engine.add_rule("I want to watch something scary", "The Conjuring is a good horror film.")
rule_engine.add_rule("I like sci-fi", "You should watch Blade Runner 2049.")
rule_engine.add_rule("any action movie", "Mad Max: Fury Road is intense!")
rule_engine.add_rule("give me a drama", "Manchester by the Sea is a strong drama.")
rule_engine.add_rule("romantic movie", "The Notebook is a classic romantic movie.")
rule_engine.add_rule("what's a good thriller", "Gone Girl will keep you guessing.")
rule_engine.add_rule("show me a fantasy movie", "The Lord of the Rings is perfect.")
rule_engine.add_rule("what's a good mystery movie", "Knives Out is a modern mystery.")
rule_engine.add_rule("I want a family movie", "Try watching Paddington 2.")
rule_engine.add_rule("suggest a kids movie", "Toy Story is always a hit.")
rule_engine.add_rule("recommend a classic movie", "Casablanca is a timeless classic.")
rule_engine.add_rule("suggest something new", "Everything Everywhere All At Once is amazing.")
rule_engine.add_rule("any new movies", "You could check out Dune: Part Two.")
rule_engine.add_rule("good movie from 2023", "Oppenheimer was a big hit in 2023.")
rule_engine.add_rule("good netflix movie", "The Irishman is a Netflix original.")
rule_engine.add_rule("disney movie recommendation", "Encanto is a fun Disney film.")
rule_engine.add_rule("what to watch on hulu", "Palm Springs is great on Hulu.")
rule_engine.add_rule("suggest something emotional", "A Silent Voice is deeply emotional.")
rule_engine.add_rule("suggest something inspiring", "The Pursuit of Happyness will inspire you.")
rule_engine.add_rule("recommend a biography", "Bohemian Rhapsody is a solid pick.")
rule_engine.add_rule("based on true story", "Catch Me If You Can is fascinating.")
rule_engine.add_rule("crime movie", "The Departed is a great crime thriller.")
rule_engine.add_rule("suggest a superhero movie", "Spider-Man: No Way Home is epic.")
rule_engine.add_rule("marvel movie", "Avengers: Endgame is a must-watch.")
rule_engine.add_rule("dc movie", "The Batman (2022) is a great DC film.")
rule_engine.add_rule("recommend anime movie", "Your Name is a beautiful anime.")
rule_engine.add_rule("feel-good movie", "The Intouchables is heartwarming.")
rule_engine.add_rule("sad movie", "Grave of the Fireflies is very moving.")
rule_engine.add_rule("what movie to cry to", "Bridge to Terabithia is a tearjerker.")
rule_engine.add_rule("something romantic", "Before Sunrise is a romantic gem.")
rule_engine.add_rule("what to watch when bored", "Scott Pilgrim vs. The World is fun!")
rule_engine.add_rule("suggest a holiday movie", "Home Alone is perfect for the holidays.")
rule_engine.add_rule("halloween movie", "Hocus Pocus is a Halloween favorite.")
rule_engine.add_rule("christmas movie", "Elf is great for Christmas.")
rule_engine.add_rule("movie for date night", "La La Land is perfect for date night.")
rule_engine.add_rule("suggest something epic", "Gladiator is truly epic.")
rule_engine.add_rule("I want an indie movie", "Lady Bird is an acclaimed indie film.")
rule_engine.add_rule("underrated movie", "Prisoners is very underrated.")
rule_engine.add_rule("overrated movie", "That's subjective, but some say Avatar.")
rule_engine.add_rule("what’s your favorite movie", "I really like Her by Spike Jonze.")
rule_engine.add_rule("I like war movies", "1917 is visually stunning.")
rule_engine.add_rule("recommend a musical", "The Greatest Showman is energetic.")
rule_engine.add_rule("suggest animation", "Coco is both beautiful and emotional.")
rule_engine.add_rule("good documentary", "13th is a powerful documentary.")
rule_engine.add_rule("suggest a heist movie", "Ocean’s Eleven is a stylish pick.")
rule_engine.add_rule("good foreign film", "Parasite is excellent.")
rule_engine.add_rule("recommend a korean movie", "Train to Busan is thrilling!")
rule_engine.add_rule("suggest a french movie", "Amélie is whimsical and sweet.")
rule_engine.add_rule("what’s trending now", "Barbie is very popular right now.")
rule_engine.add_rule("suggest something unique", "Swiss Army Man is quite unique!")
rule_engine.add_rule("what's good on amazon prime", "Sound of Metal is fantastic.")
rule_engine.add_rule("I like detective stories", "Zodiac is gripping.")
rule_engine.add_rule("suggest a courtroom drama", "A Few Good Men is a solid choice.")
rule_engine.add_rule("what’s a good romance", "Pride and Prejudice (2005) is beautiful.")
rule_engine.add_rule("suggest a noir film", "Chinatown is classic noir.")
rule_engine.add_rule("movie with twist ending", "The Sixth Sense is unforgettable.")
rule_engine.add_rule("time travel movie", "Looper is clever and entertaining.")
rule_engine.add_rule("dystopian movie", "Children of Men is a powerful dystopia.")
rule_engine.add_rule("apocalypse movie", "I Am Legend is a good one.")
rule_engine.add_rule("zombie movie", "28 Days Later is excellent.")
rule_engine.add_rule("vampire movie", "Let the Right One In is haunting.")
rule_engine.add_rule("werewolf movie", "An American Werewolf in London is iconic.")
rule_engine.add_rule("space movie", "Gravity is visually stunning.")
rule_engine.add_rule("deep sci-fi", "Annihilation is a mind-bender.")
rule_engine.add_rule("slow-burn thriller", "The Gift is a chilling slow burn.")
rule_engine.add_rule("suggest a romantic comedy", "Crazy Rich Asians is hilarious and sweet.")
rule_engine.add_rule("teen movie", "Mean Girls is a teen classic.")
rule_engine.add_rule("movie about friendship", "Stand By Me is about lifelong bonds.")
rule_engine.add_rule("suggest a western", "The Good, the Bad and the Ugly is iconic.")
rule_engine.add_rule("recommend a short movie", "World of Tomorrow is a great short film.")
rule_engine.add_rule("mind-bending movie", "Tenet will challenge your brain!")
rule_engine.add_rule("quiet movie", "Lost in Translation is subtle and beautiful.")
rule_engine.add_rule("loud movie", "Transformers is full of action and noise!")
rule_engine.add_rule("suggest something historical", "Schindler's List is a must-watch.")
rule_engine.add_rule("based on a book", "Little Women (2019) is a great adaptation.")
rule_engine.add_rule("epic fantasy", "Game of Thrones (series) is legendary.")
rule_engine.add_rule("suggest a sports movie", "Remember the Titans is motivational.")
rule_engine.add_rule("movie with great visuals", "Avatar: The Way of Water is stunning.")
rule_engine.add_rule("underrated animation", "The Iron Giant is amazing.")
rule_engine.add_rule("movie with good music", "Baby Driver has a great soundtrack.")
rule_engine.add_rule("suggest a dark comedy", "Fargo is dark but hilarious.")
rule_engine.add_rule("recommend something stylish", "Drive is visually striking.")
rule_engine.add_rule("suggest a cult classic", "Donnie Darko is a cult hit.")
rule_engine.add_rule("something like inception", "Try watching Shutter Island.")
rule_engine.add_rule("what to watch tonight", "You can't go wrong with Forrest Gump.")
rule_engine.add_rule("I like animated movies", "Spider-Man: Into the Spider-Verse is great.")
rule_engine.add_rule("recommend something chill", "Chef is a relaxing, feel-good movie.")
rule_engine.add_rule("suggest a movie about robots", "Ex Machina is fascinating.")
rule_engine.add_rule("what's a good horror", "Hereditary is truly terrifying.")
rule_engine.add_rule("I want a long movie", "The Irishman is nearly 4 hours long!")
rule_engine.add_rule("I want a short movie", "My Neighbor Totoro is under 90 minutes.")

# Have conversation
while True:
    user_input = input("You: ")
    response = rule_engine.apply_rules(user_input)
    print(response)
    
    if user_input.lower() == "goodbye":
      break